"""new fields in user model

Revision ID: 53b8df8e65e5
Revises: 8a924119b6ef
Create Date: 2023-04-05 11:13:12.422842

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '53b8df8e65e5'
down_revision = '8a924119b6ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
